name: Zara Stok Kontrol

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları indir
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Paketleri yükle
        run: |
          pip install -r requirements.txt

      - name: Zara stok kontrolü
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python monitor.py
